---
title: "Merge Illinois APR and SAIPE"
author: "Joy Dada"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmdformats::robobook
---

# Introduction

This script merges the Illinois APR CFCs and the SAPIE Poverty Data.

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

path_box <- 
  file.path(
    Sys.getenv("BOX"),
    "Child Care and Poverty"
  )

require("pacman")

packages <-
  c("tidyverse",
    "ggplot2",
    "readxl",
    "haven",
    "tidyr",
    "openxlsx",
    "remotes",
    "janitor",
    "expss",
    "dplyr",
    "statar",
    "dataReporter",
    "here",
    "ggeasy",
    "extrafont",
    "sjlabelled",
    "wesanderson",
    "kableExtra",
    "epiDisplay",
    "lfe",
    "stargazer"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```


# Import data

## 2014-2017 Illinois APR

```{r}
delays <-
  readRDS(
    here(
    path_box,
    "Data",
    "constructed",
    "APR 2014-2017 delays.rds"
    )
  )
```

## SAIPE

```{r}
poverty <-
   readRDS(
     here(
       path_box,
       "Data",
       "constructed",
       "SAIPE Poverty County Estimates 2004-2021"
       )
   )
```





