---
title: "Import and arrange 2004-2022 MO Population Data"
author: "Joy Dada"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: rmdformats::robobook
---

# Introduction

This script imports and arranges the [historical population data](https://www.macrotrends.net/states/missouri/population).

```{r setup, include = FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Change to Box folder on your computer

path_box <- 
  file.path(
    Sys.getenv("BOX"),
    "Child Care and Poverty"
  )

# Load necessary packages

require("pacman")

packages <-
  c("tidyverse",
    "ggplot2",
    "readxl",
    "haven",
    "tidyr",
    "openxlsx",
    "remotes",
    "janitor",
    "expss",
    "dplyr",
    "statar",
    "dataReporter",
    "here",
    "ggeasy",
    "extrafont",
    "sjlabelled",
    "wesanderson",
    "kableExtra",
    "epiDisplay",
    "lfe",
    "stargazer"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```




# Import historical population data

```{r}
hist_pop <-
  read.csv(
    here(
      path_box,
      "Data",
      "raw-deidentified",
      "missouri-population-2023-10-14.csv"
    ),
    skip = 15,
    head = TRUE,
    sep = ","
  )

saveRDS(
  hist_pop,
  here(
      path_box,
      "Data",
      "raw-deidentified",
      "missouri-population-2023-10-14.rds"
    )
)
```

## Clean historical population 2004-2023

```{r}
hist_clean  <-
  hist_pop %>% 
  clean_names() %>% 
  mutate(
    year = as.numeric(substr(date, 1, 4)),
    tot_pop = as.numeric(population)
  ) %>% 
  filter(
    year >= 2004
  ) %>% 
  dplyr::select(
    year,
    tot_pop
  ) 

saveRDS(
  hist_clean,
   here(
      path_box,
      "Data",
      "constructed",
      "missouri-population-2004-2022.rds"
    )
)
```